### ISSUE TITLE
Review errordetector and dcerrordetector module 

### ISSUE THREAD

**Issue by ah89** [HoloClean/HoloClean-Legacy-deprecated#21]
As we followed new structure , May I ask you to take look at dcerrordetector and  errordetector , ask me to check part you think it might have error .

Thank in advance

**Comment by gmichalo** [comment]
After the code for the errordetector was reviewed i think we could do the following changes:
1. The init method should have comments

2.The import sys, sys.path.append('../') should be removed. (If we run the code from a parent directory we will not have a problem)

3. in order to check the code with pep8 one good practice (that I also need to start following for my code) we need to have whitespace after ',' and we need to have lines that are not very long (over 79 characters)

**Comment by ah89** [comment]
1. cause the init is constructor of class I add short description in each constructor and part of it came in general description for class

2. Done!

3. Done!
