### ISSUE TITLE
Remove comments from holoclean.py

### ISSUE THREAD

**Issue by thodrek** [HoloClean/HoloClean-Legacy-deprecated#26]
If something is not implemented if should be annotated with a TODO. Not commented out.

**Comment by gmichalo** [comment]
Done!
In addition i changed the position of 

self.dataengine = self._init_dataengine()
self.spark_session, self.spark_sql_ctxt = self._init_spark()

to 


self.spark_session, self.spark_sql_ctxt = self._init_spark()
self.dataengine = self._init_dataengine()

because dataengine needs the self.spark_sql_ctxt for its init method
